# We start with an existing image
FROM node:20

# Working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY ./package.json ./package-lock.json ./

# Install dependencies
RUN npm i

# Copy the code into the container
COPY . .

# Expose port 3000
#EXPOSE 3000

# Launch the application
CMD [ "npm", "start" ]